export const CHANGE_PLAYER = 'CHANGE_PLAYER'

export const HIT_CARD = 'HIT_CARD'

export const FETCH_CARDS_REQUEST = 'FETCH_CARDS_REQUEST'
export const FETCH_CARDS_FAILURE = 'FETCH_CARDS_FAILURE'
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS'
